######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 5 21:47:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . res src ui
INCLUDEPATH += . src

# Input
HEADERS += src/mainwindow.h src/qpanexapp.h
FORMS += ui/mainwindow.ui
SOURCES += src/main.cpp src/mainwindow.cpp src/qpanexapp.cpp
RESOURCES += res/panexres.qrc
